version: '3'

services:
  minio:
   image: minio/minio:RELEASE.2021-10-02T16-31-05Z
   container_name: minio
   ports:
     - 9000:9000
     - 9001:9001
   environment:
     #
     # !!! CHANGE THESE !!!
     #
     MINIO_ACCESS_KEY: mightyadmin
     MINIO_SECRET_KEY: supersecret
   volumes:
     - ./data:/data
   restart: unless-stopped
   command: minio server --console-address :9001 /data

