# docker build -t minio:RELEASE.2023-08-23T10-07-06Z .
# docker run -d --name minio -e "MINIO_ROOT_USER=username" -e "MINIO_ROOT_PASSWORD=password" -e "MINIO_HTTP_TRACE=/tmp/minio.log" -e "MINIO_SERVER_URL=https://193.225.250.14:10000" -p 10001:9001 -p 10000:9000 minio:RELEASE.2022-03-17T06-34-49Z

FROM minio/minio:RELEASE.2023-08-23T10-07-06Z

RUN mkdir -p /root/.minio/certs/CAs
# cat {server.crt,ca.crt} > ca-and-server-cert.crt
COPY ./certificates/ca-and-server-cert.crt /root/.minio/certs/CAs/public.crt
COPY ./certificates/server-key.pem /root/.minio/certs/private.key
COPY ./certificates/server-cert.pem /root/.minio/certs/public.crt
# RUN chmod 600 /root/.minio/certs/*
# RUN chown minio:minio /root/.minio/certs/*

CMD ["server", "/data", "--certs-dir", "/root/.minio/certs", "--console-address", ":9001"]